[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  BROWSER = "none"
  PORT = "3000"
  CI = "false"
  NODE_VERSION = "18"
  # HubSpot and Apollo environment variables should be set in the Netlify UI
  # Required variables: APOLLO_API_KEY, SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY
  # DO NOT add sensitive values here

# This handles the single-page application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Note: Sensitive environment variables like API keys should be set in the Netlify UI
# This file only contains non-sensitive configuration 