[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  BROWSER = "none"
  PORT = "3002"
  CI = "false"
  NODE_VERSION = "18"
  # Environment variables should be set in the Netlify UI
  # Required variables: APOLLO_API_KEY, SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, HUBSPOT_ACCESS_TOKEN, MIGRATION_SECRET_KEY
  # For Slack-Claude integration: SLACK_BOT_TOKEN, SLACK_SIGNING_SECRET, SLACK_APP_TOKEN, ANTHROPIC_API_KEY
  # DO NOT add sensitive values here

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@hubspot/api-client", "@slack/bolt", "@slack/web-api", "@anthropic-ai/sdk"]

# API endpoint redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# This handles the single-page application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Note: Sensitive environment variables like API keys should be set in the Netlify UI
# This file only contains non-sensitive configuration

[dev]
  publish = "public"
  targetPort = 3002
  port = 8889